name: face_simulator_frontend
description: Flutter web frontend for Face Simulator with warping capabilities
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI 컴포넌트
  cupertino_icons: ^1.0.2
  
  # HTTP 클라이언트
  http: ^1.1.0
  dio: ^5.3.2
  
  # 이미지 처리
  image: ^4.1.3
  image_picker: ^1.0.4
  
  # 파일 선택
  file_picker: ^6.1.1
  
  # 상태 관리
  provider: ^6.1.1
  
  # JSON 파싱
  json_annotation: ^4.8.1
  
  # 기타 유틸리티
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # 차트 라이브러리
  fl_chart: ^0.69.0
  
  # URL 런처
  url_launcher: ^6.2.2
  
  # Google Fonts
  google_fonts: ^6.1.0
  
  # 카메라
  camera: ^0.10.5+9
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/